import tkinter as tk

class InfosUI(tk.LabelFrame):
    def __init__(self, fenetre, **kwargs):
        tk.LabelFrame.__init__(self, fenetre, text="Infos", padx=10, pady=80, width=250, **kwargs) 
        self.grid(sticky="ns")

        self._labelSource = tk.Label(self, text="Source :", width=12, anchor="w")
        self.labelSourceReponse = tk.Label(self, text="", width=20, anchor="w")
        self._labelAnnee = tk.Label(self, text="Année :", width=12, anchor="w")
        self.labelAnneeReponse = tk.Label(self, text="", width=20, anchor="w")
        self._labelRealisateur = tk.Label(self, text="Réalisateur :", width=12, anchor="w")
        self.labelRealisateurReponse = tk.Label(self, text="", width=20, anchor="w")
        self._labelPays = tk.Label(self, text="Pays :", width=12, anchor="w")
        self.labelPaysReponse = tk.Label(self, text="", width=20, anchor="w")
        self._labelActeurs = tk.Label(self, text="Acteurs :", width=12, anchor="w")
        self.labelActeursReponse = tk.Label(self, text="", width=20, anchor="w")

        self._labelEspaceVide = tk.Label(self, width=10)
        self.labelActeurs2Reponse = tk.Label(self, width=20, anchor="w")
        self.labelActeurs3Reponse = tk.Label(self, width=20, anchor="w")
        
        self._labelOperateur = tk.Label(self, text="Opérateur :", width=15, anchor="w")
        self.labelOperateurReponse = tk.Label(self, text="", width=15, anchor="w")
        self._labelEmulsion = tk.Label(self, text="Emulsion :", width=15, anchor="w")
        self.labelEmulsionReponse = tk.Label(self, text="", width=15, anchor="w")        
        self._labelFormat = tk.Label(self, text="Format :", width=15, anchor="w")
        self.labelFormatReponse = tk.Label(self, text="", width=15, anchor="w")
        self._labelAmbiance = tk.Label(self, text="Ambiance / Lieux :", width=15, anchor="w")
        self.labelAmbianceReponse = tk.Label(self, text="", width=15, anchor="w")
        self._labelFocale = tk.Label(self, text="Focale :", width=15, anchor="w")
        self.labelFocaleReponse = tk.Label(self, text="", width=15, anchor="w")
        self._labelCommentaire = tk.Label(self, text="Commentaires :", width=12, anchor="w")
        self.labelCommentaireReponse = tk.Label(self, text="", width=20, anchor="w")
        
        self._labelSource.grid(row=0, column=0)
        self.labelSourceReponse.grid(row=0, column=1)
        self._labelAnnee.grid(row=1, column=0)
        self.labelAnneeReponse.grid(row=1, column=1)
        self._labelRealisateur.grid(row=2, column=0)
        self.labelRealisateurReponse.grid(row=2, column=1)
        self._labelPays.grid(row=3, column=0)
        self.labelPaysReponse.grid(row=3, column=1)
        self._labelActeurs.grid(row=4, column=0)
        self.labelActeursReponse.grid(row=4, column=1)

        self._labelEspaceVide.grid(row=0, column=2)
        self.labelActeurs2Reponse.grid(row=5, column=1)
        self.labelActeurs3Reponse.grid(row=6, column=1)

        self._labelOperateur.grid(row=0, column=3)
        self.labelOperateurReponse.grid(row=0, column=4)
        self._labelEmulsion.grid(row=1, column=3)
        self.labelEmulsionReponse.grid(row=1, column=4)
        self._labelFocale.grid(row=2, column=3)
        self.labelFocaleReponse.grid(row=2, column=4)
        self._labelFormat.grid(row=3, column=3)
        self.labelFormatReponse.grid(row=3, column=4)
        self._labelAmbiance.grid(row=4, column=3)
        self.labelAmbianceReponse.grid(row=4, column=4)
        self._labelCommentaire.grid(row=7, column=0)
        self.labelCommentaireReponse.grid(row=8, column=0, columnspan=2)