import tkinter as tk

class FenetreAjouter(tk.Toplevel):
    def __init__(self, fenetre):
        tk.Toplevel.__init__(self, fenetre)
        self.cadre = tk.LabelFrame(self, text="Ajouter une image", padx=15, pady=12)
        self.cadre.grid()
        self.resizable(False, False)

        self._labelSource = tk.Label(self.cadre, text="Source :", width=12, anchor="w")
        self.labelSourceReponse = tk.Entry(self.cadre, width=20)
        self._labelAnnee = tk.Label(self.cadre, text="Année :", width=12, anchor="w")
        self.labelAnneeReponse = tk.Entry(self.cadre, width=20)
        self._labelPays = tk.Label(self.cadre, text="Pays :", width=12, anchor="w")
        self.labelPaysReponse = tk.Entry(self.cadre, width=20)
        self._labelRealisateur = tk.Label(self.cadre, text="Réalisateur :", width=12, anchor="w")
        self.labelRealisateurReponse = tk.Entry(self.cadre, width=20)
        self._labelOperateur = tk.Label(self.cadre, text="Opérateur :", width=12, anchor="w")
        self.labelOperateurReponse = tk.Entry(self.cadre, width=20)
        self._labelActeurs1 = tk.Label(self.cadre, text="Acteur 1 :", width=12, anchor="w")
        self.labelActeurs1Reponse = tk.Entry(self.cadre, width=20)
        self._labelActeurs2 = tk.Label(self.cadre, text="Acteur 2 :", width=12, anchor="w")
        self.labelActeurs2Reponse = tk.Entry(self.cadre, width=20)
        self._labelActeurs3 = tk.Label(self.cadre, text="Acteur 3 :", width=12, anchor="w")
        self.labelActeurs3Reponse = tk.Entry(self.cadre, width=20)
        self._labelGenre = tk.Label(self.cadre, text="Genre :", width=12, anchor="w")
        self.labelGenreReponse = tk.Entry(self.cadre, width=20)
        self._labelValeur = tk.Label(self.cadre, text="Valeur de plan :", width=12, anchor="w")
        self.labelValeurReponse = tk.Entry(self.cadre, width=20)

        self._labelEspaceVide = tk.Label(self.cadre, width=10)
        self._labelLigneVide1 = tk.Label(self.cadre)
        self._labelLigneVide2 = tk.Label(self.cadre)
        
        self._labelEmulsion = tk.Label(self.cadre, text="Emulsion :", width=15, anchor="w")
        self.labelEmulsionReponse = tk.Entry(self.cadre, width=15)        
        self._labelFocale = tk.Label(self.cadre, text="Focale :", width=15, anchor="w")
        self.labelFocaleReponse = tk.Entry(self.cadre, width=15)
        self._labelFormat = tk.Label(self.cadre, text="Format :", width=15, anchor="w")
        self.labelFormatReponse = tk.Entry(self.cadre, width=15)
        self._labelAmbiance = tk.Label(self.cadre, text="Ambiance :", width=15, anchor="w")
        self.labelAmbianceReponse = tk.Entry(self.cadre, width=15)
        self._labelLieux = tk.Label(self.cadre, text="Lieux :", width=15, anchor="w")
        self.labelLieuxReponse = tk.Entry(self.cadre, width=15)        
        self._labelContraste = tk.Label(self.cadre, text="Constraste :", width=15, anchor="w")
        self.labelContrasteReponse = tk.Entry(self.cadre, width=15)
        self._labelCouleur1 = tk.Label(self.cadre, text="Couleur1 :", width=15, anchor="w")
        self.labelCouleur1Reponse = tk.Entry(self.cadre, width=15)
        self._labelCouleur2 = tk.Label(self.cadre, text="Couleur2 :", width=15, anchor="w")
        self.labelCouleur2Reponse = tk.Entry(self.cadre, width=15)
        self._labelCouleur3 = tk.Label(self.cadre, text="Couleur3 :", width=15, anchor="w")
        self.labelCouleur3Reponse = tk.Entry(self.cadre, width=15)
        self._labelNatureDesSources = tk.Label(self.cadre, text="Sources de lum. :", width=15, anchor="w")
        self.labelNatureDesSourcesReponse = tk.Entry(self.cadre, width=15)

        self._labelCommentaire = tk.Label(self.cadre, text="Commentaires :", width=12, anchor="w")
        self.labelCommentaireReponse = tk.Entry(self.cadre, width=40)
        self._labelPathImage = tk.Label(self.cadre, text="Path Image :", width=12, anchor="w")
        self.labelPathImageReponse = tk.Entry(self.cadre, width=40)
        self.boutonEnvoyer = tk.Button(self.cadre, text="Envoyer", width=20)

        self._labelSource.grid(row=0, column=0)
        self.labelSourceReponse.grid(row=0, column=1)
        self._labelAnnee.grid(row=1, column=0)
        self.labelAnneeReponse.grid(row=1, column=1)
        self._labelPays.grid(row=2, column=0)
        self.labelPaysReponse.grid(row=2, column=1)
        self._labelRealisateur.grid(row=3, column=0)
        self.labelRealisateurReponse.grid(row=3, column=1)
        self._labelOperateur.grid(row=4, column=0)
        self.labelOperateurReponse.grid(row=4, column=1)
        self._labelActeurs1.grid(row=5, column=0)
        self.labelActeurs1Reponse.grid(row=5, column=1)
        self._labelActeurs2.grid(row=6, column=0)
        self.labelActeurs2Reponse.grid(row=6, column=1)
        self._labelActeurs3.grid(row=7, column=0)
        self.labelActeurs3Reponse.grid(row=7, column=1)
        self._labelGenre.grid(row=8, column=0)
        self.labelGenreReponse.grid(row=8, column=1)
        self._labelValeur.grid(row=9, column=0)
        self.labelValeurReponse.grid(row=9, column=1)

        self._labelEspaceVide.grid(row=0, column=2)
        self._labelLigneVide1.grid(row=10, column=0)

        self._labelEmulsion.grid(row=0, column=3)
        self.labelEmulsionReponse.grid(row=0, column=4)
        self._labelFocale.grid(row=1, column=3)
        self.labelFocaleReponse.grid(row=1, column=4)
        self._labelFormat.grid(row=2, column=3)
        self.labelFormatReponse.grid(row=2, column=4)
        self._labelAmbiance.grid(row=3, column=3)
        self.labelAmbianceReponse.grid(row=3, column=4)
        self._labelLieux.grid(row=4, column=3)
        self.labelLieuxReponse.grid(row=4, column=4)
        self._labelContraste.grid(row=5, column=3)
        self.labelContrasteReponse.grid(row=5, column=4)
        self._labelCouleur1.grid(row=6, column=3)
        self.labelCouleur1Reponse.grid(row=6, column=4)
        self._labelCouleur2.grid(row=7, column=3)
        self.labelCouleur2Reponse.grid(row=7, column=4)
        self._labelCouleur3.grid(row=8, column=3)
        self.labelCouleur3Reponse.grid(row=8, column=4)
        self._labelNatureDesSources.grid(row=9, column=3)
        self.labelNatureDesSourcesReponse.grid(row=9, column=4)

        self._labelCommentaire.grid(row=11, column=0)
        self.labelCommentaireReponse.grid(row=12, column=0, columnspan=3)
        self._labelLigneVide2.grid(row=13, column=0)

        self._labelPathImage.grid(row=14, column=0)
        self.labelPathImageReponse.grid(row=15, column=0, columnspan=3)

        self.boutonEnvoyer.grid(row=15, column=4)